name: Publish

on:
  push:
    branches:
      - main

jobs:
  check-version:
    uses: ./.github/workflows/check-version.yml
    
  publish:
    needs: check-version
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
